// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	userv1 "github.com/Homyakadze14/AuthMicroservice/proto/gen/user"
)

// UserServiceI is an autogenerated mock type for the UserServiceI type
type UserServiceI struct {
	mock.Mock
}

// CreateDefault provides a mock function with given fields: ctx, in, opts
func (_m *UserServiceI) CreateDefault(ctx context.Context, in *userv1.CreateDefaultRequest, opts ...grpc.CallOption) (*userv1.CreateDefaultResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateDefault")
	}

	var r0 *userv1.CreateDefaultResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *userv1.CreateDefaultRequest, ...grpc.CallOption) (*userv1.CreateDefaultResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *userv1.CreateDefaultRequest, ...grpc.CallOption) *userv1.CreateDefaultResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userv1.CreateDefaultResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *userv1.CreateDefaultRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserServiceI creates a new instance of UserServiceI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceI(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceI {
	mock := &UserServiceI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
