basePath: /api/v1
definitions:
  authv1.ActivateAccountResponse:
    properties:
      success:
        type: boolean
    type: object
  authv1.ChangePasswordResponse:
    properties:
      success:
        type: boolean
    type: object
  authv1.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  authv1.LogoutResponse:
    properties:
      success:
        type: boolean
    type: object
  authv1.RefreshResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  authv1.RegisterResponse:
    properties:
      success:
        type: boolean
    type: object
  authv1.SendPasswordLinkResponse:
    properties:
      success:
        type: boolean
    type: object
  entities.ActivateAccountRequest:
    properties:
      link:
        type: string
    required:
    - link
    type: object
  entities.ChangePasswordRequest:
    properties:
      link:
        type: string
      password:
        maxLength: 50
        minLength: 8
        type: string
    required:
    - link
    - password
    type: object
  entities.LoginRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 50
        minLength: 8
        type: string
      username:
        type: string
    required:
    - password
    type: object
  entities.LogoutRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  entities.RefreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  entities.RegisterRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 50
        minLength: 8
        type: string
      username:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
  entities.SendPasswordLinkRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
host: cookhub.space
info:
  contact: {}
  description: API Gatewate for orbit of success services
  title: API Gatewate
  version: "1.0"
paths:
  /auth/activate_account:
    post:
      consumes:
      - application/json
      description: Activate account
      operationId: Activate account
      parameters:
      - description: activate
        in: body
        name: activate
        schema:
          $ref: '#/definitions/entities.ActivateAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authv1.ActivateAccountResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Activate account
      tags:
      - Auth
  /auth/change_password:
    post:
      consumes:
      - application/json
      description: Change password
      operationId: Change password
      parameters:
      - description: password
        in: body
        name: password
        schema:
          $ref: '#/definitions/entities.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authv1.ChangePasswordResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Change password
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      operationId: Login
      parameters:
      - description: login
        in: body
        name: login
        schema:
          $ref: '#/definitions/entities.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authv1.LoginResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Login
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout
      operationId: Logout
      parameters:
      - description: logout
        in: body
        name: logout
        schema:
          $ref: '#/definitions/entities.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authv1.LogoutResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Logout
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh token
      operationId: Refresh token
      parameters:
      - description: refresh
        in: body
        name: refresh
        schema:
          $ref: '#/definitions/entities.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authv1.RefreshResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Refresh token
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register
      operationId: Register
      parameters:
      - description: register
        in: body
        name: register
        schema:
          $ref: '#/definitions/entities.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authv1.RegisterResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Register
      tags:
      - Auth
  /auth/send_password_link:
    post:
      consumes:
      - application/json
      description: Send password link
      operationId: Send password link
      parameters:
      - description: email
        in: body
        name: email
        schema:
          $ref: '#/definitions/entities.SendPasswordLinkRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authv1.SendPasswordLinkResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Send password link
      tags:
      - Auth
schemes:
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
