env: "local"  

http:
  port: 8080

auth_service:
  address: "localhost:5000"

user_service:
  address: "localhost:5001"

course_service:
  address: "localhost:5002"


s3:
  access_key: ""
  secret_access_key: ""
  bucket_name: ""
  endpoint: ""