env: "local"  

GRPC:
  port: 5000
  timeout: 5s

database:
  url: "postgres://postgres:postgres@localhost:5433/authmicroservice"  
  pool_max: 2

jwt_access:
  secret: "jwt_access_secret_key"
  duration: 15m

jwt_refresh:
  secret: "jwt_refresh_secret_key"
  duration: 30d

mailer:
  username: "username"
  password: "password"
  host: "host"
  addr: "addr"

base_links:
  activation_url: "http://localhost:5000/activate/"
  change_password_url: "http://localhost:5000/change_password/"

user_service:
  address: "localhost:5001"