CREATE TABLE IF NOT EXISTS user_info(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT UNIQUE NOT NULL, 
    firstname VARCHAR(250) NOT NULL,
    middlename VARCHAR(250) NOT NULL,
    lastname VARCHAR(250) NOT NULL,
    gender VARCHAR(1) NOT NULL,
    phone VARCHAR(250) NOT NULL,
    icon_url VARCHAR(400) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);